# fish completion for fermix, installed by the fermix package.
# The verb list is the one `fermix help` prints; a test keeps them in step.

set -l fermix_verbs setup auth ask chat run sandbox grant revoke service start stop restart status health voice acp agents capabilities skills plugins pair devices memory logs upgrade uninstall migrate-to-app doctor diagnostics version help

complete -c fermix -f

complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a setup -d "Run the setup assistant"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a auth -d "Sign in to a provider account"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a ask -d "Send one message to the assistant"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a chat -d "Hold a conversation in the terminal"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a run -d "Run the daemon in the foreground"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a sandbox -d "Inspect and change directory access"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a grant -d "Grant access to one directory"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a revoke -d "Withdraw a directory grant"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a service -d "Manage the background service"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a start -d "Start the background service"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a stop -d "Stop the background service"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a restart -d "Restart the background service"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a status -d "Show daemon status"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a health -d "Show daemon health"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a voice -d "Show voice companion status"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a acp -d "Bridge an agent client to the daemon"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a agents -d "Show agent status"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a capabilities -d "Show registered capabilities"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a skills -d "Inspect and reload skills"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a plugins -d "Manage plugins"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a pair -d "Pair a mobile device"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a devices -d "List and revoke paired devices"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a memory -d "Review and restore memory"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a logs -d "Show the daemon log file"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a upgrade -d "Update the engine"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a uninstall -d "Remove an app-managed install"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a migrate-to-app -d "Move a formula install to the app"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a doctor -d "Run post-install diagnostics"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a diagnostics -d "Collect a redacted support bundle"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a version -d "Print the version"
complete -c fermix -n "not __fish_seen_subcommand_from $fermix_verbs" -a help -d "Print the command summary"

complete -c fermix -n "__fish_seen_subcommand_from service" -a "install uninstall status run"
complete -c fermix -n "__fish_seen_subcommand_from auth" -a "login status logout"
complete -c fermix -n "__fish_seen_subcommand_from skills" -a "list view reload"
complete -c fermix -n "__fish_seen_subcommand_from plugins" -a "list catalog install enable disable auth"
complete -c fermix -n "__fish_seen_subcommand_from devices" -a "list revoke"
complete -c fermix -n "__fish_seen_subcommand_from memory" -a "review restore"
complete -c fermix -n "__fish_seen_subcommand_from acp" -a "forget"
complete -c fermix -n "__fish_seen_subcommand_from diagnostics" -a "export"
complete -c fermix -n "__fish_seen_subcommand_from diagnostics" -l offline -d "Collect without a running daemon"
complete -c fermix -n "__fish_seen_subcommand_from service install status uninstall status health agents voice ask chat capabilities skills plugins memory diagnostics restart" -l json -d "Print a machine-readable envelope"
complete -c fermix -n "__fish_seen_subcommand_from service install" -l home -r -d "The Fermix home this service runs from"
complete -c fermix -n "__fish_seen_subcommand_from service install" -l port -r -d "The listener port"
complete -c fermix -n "__fish_seen_subcommand_from doctor status" -l full -d "Show every check"
complete -c fermix -n "__fish_seen_subcommand_from restart" -l when-idle -d "Wait for idle before restarting"
complete -c fermix -n "__fish_seen_subcommand_from upgrade" -l check -d "Report without updating"
complete -c fermix -n "__fish_seen_subcommand_from migrate-to-app" -l yes -d "Perform the transaction"
